name : CI Workflow Automation
on : push

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
       # Get Code
       - name: Run custom action from root
         uses: ./.github/actions/ci-check


     
        
     
    
